#!/usr/bin/env ruby

STDOUT.sync = true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require 'jekyll_page_boilerplate'
require "mercenary"

Mercenary.program(:boilerplate) do |p|
  p.version JekyllPageBoilerplate::VERSION
  p.description 'jekyll-page-boilerplate is a gem for jekyll that helps you generate new pages'
  p.syntax "jekyll-page <subcommand> [options]"

  p.command(:page) do |c|
    c.syntax "create BOILERPLATE_NAME \"NEW PAGE TITLE\""
    c.description "Creates a page or post from a boilerplate."

    c.action do |args, _|
      JekyllPageBoilerplate.page args[0], args[1], c
    end
  end

  p.command(:help) do |c|
    c.syntax "help"
    c.description "Describe what jekyll-page-boilerplate does."

    c.action do
      JekyllPageBoilerplate.help c
    end
  end


  p.default_command(:help)
end


