#!/usr/bin/env ruby

STDOUT.sync = true

gem_dir = File.expand_path("..",File.dirname(__FILE__))
$LOAD_PATH.unshift gem_dir # Look in gem directory for resources first.

require 'jekyll_page_boilerplate_cli'
